### ISSUE TITLE
Работа с property

### ISSUE THREAD

**Issue by mousanonyad** [zhenianik/LaZhStudyEnglishWords#3]
https://github.com/zhenianik/LaZhStudyEnglishWords/blob/a685a79fcd307af75f7fd5f72796826d2185c50e/src/main/java/Bot.java#L42-L64

Если оставлять как есть, то убрать абсолютный путь к диску, сделать его относительным проекта.
Но я не понял зачем вычитывать все в мапу? Работать напрямую с проперти, положив их в resources.

**Comment by zhenianik** [comment]
ok
