### ISSUE TITLE
Перейти на try-with-resources.

### ISSUE THREAD

**Issue by mousanonyad** [zhenianik/LaZhStudyEnglishWords#5]
https://github.com/zhenianik/LaZhStudyEnglishWords/blob/a685a79fcd307af75f7fd5f72796826d2185c50e/src/main/java/Translator.java#L41

Сейчас при любом исключении ресурс не будет закрыт.
Так же можно немного изменить код, в статье и в комментах https://habr.com/ru/post/459080/

**Comment by zhenianik** [comment]
ok
